### ISSUE TITLE
Implement `revokeAllOperators`

### ISSUE THREAD

**Issue by jacquesd** [jacquesd/ERC777#35]
For convenience and security reasons, a new function should be added:
``` ts
function revokeAllOperators() public;
```
This method revokes all the operators for `msg.sender`.

**Comment by Quazia** [comment]
The only way I could see for revoking all authorized operators would be to track a list of authorized operators. Even if a list of authorized operators was kept there may be situations where iterating through the full list of authorized operators would cause an out of gas exception. Any ideas on how to get around this?

**Comment by jacquesd** [comment]
Yes we do, it's a bit lengthy to explain here but I will push an implementation for it in the next few days. I'll ping you so you can take a look. Any feedback is welcome!

**Comment by jacquesd** [comment]
After some thinking and discussing with a few people this will not be implemented.
