### ISSUE TITLE
Add code coverage for the reference implementation

### ISSUE THREAD

**Issue by jacquesd** [jacquesd/ERC777#36]
Code coverage must be added for the reference implementation, probably using [sc-forks/solidity-coverage](https://github.com/sc-forks/solidity-coverage) either with solcpiler or truffle.

### CI-Integration
- Code coverage must be published to [codecov.io](https://codecov.io) for each build
- A badge must be added to the readme
- A minimum coverage threshold should be enforced (80% ?)

**Comment by Quazia** [comment]
Currently, the repo is not setup to use truffle. I'm not sure there's a way to get solidity-coverage working without truffle.

**Comment by jacquesd** [comment]
No, we use [jbaylina/solcpiler](https://github.com/jbaylina/solcpiler/). I can see three approach to solve this:
1. Make solidity-coverage and solcpiler work together
2. Use truffle either alongside or instead of solcpiler
3. Find another coverage tool which work with solcpiler

Any suggestion on how to approach it is welcome!

**Comment by Quazia** [comment]
I think that using truffle is the easiest option, the main downside being the inability to use the newest versions of solidity. I'd be open to getting this setup with truffle but the contracts would need to have their import statements changed around to work with truffle so I don't think using the two alongside makes sense. I'm not aware of another coverage tool that has as much development attention as solidity-coverage. I think the main two options are:

1. Fork solidity-coverage and make it play nice with solcpiler
2. Switch the whole repo over to truffle

**Comment by jacquesd** [comment]
I did not have a look at the internal of solidity-coverage. I was hoping there would be a nice way to "connect" it with solcpiler. If it instruments truffle then I agree we must switch to truffle. In any case I need to reorganize the tests first because it's a bit of a mess and I'll have a look at truffle and solidity-coverage after.

**Comment by Quazia** [comment]
Let me know if there's anything I can do to help out.
